### ISSUE TITLE
Cambiar los banners

### ISSUE THREAD

**Issue by faustodelatog** [danielalopezmino/elbaul#14]

**Comment by danielalopezmino** [comment]
![prueba_fuerza](https://cloud.githubusercontent.com/assets/12737652/14269765/4ba058b8-faad-11e5-907d-2708d0fce5b7.jpg)
![regalos_increibles](https://cloud.githubusercontent.com/assets/12737652/14269766/4ba05dc2-faad-11e5-8fc0-97527144f26a.jpg)
![todos_lo_quieren](https://cloud.githubusercontent.com/assets/12737652/14269767/4ba0bb82-faad-11e5-8609-3fc62739fce9.jpg)
